title: Husam Gameel | Oppenheim3r
description: Cybersecurity Blog - Exploring offensive and defensive security
baseurl: ""
url: "https://oppenheim3r.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: pretty

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "blogs"
    values:
      layout: "post"
  - scope:
      path: "projects"
    values:
      layout: "post"
  - scope:
      path: "research"
    values:
      layout: "post"

